[fix]修改部署脚本

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -11,11 +11,28 @@ jobs:
     if: github.event.repository.owner.id == github.event.sender.id
 
     steps:
+      - name: Config SSH
+        env:
+          ACTION_DEPLOY_KEY: ${{ secrets.HEXO_DEPLOY_KEY }}
+        run: |
+          mkdir -p ~/.ssh/
+          
+          printf "%s" "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
+          ssh-keygen -y -f ~/.ssh/id_rsa || echo "Invalid key format"
+          
+          chmod 700 ~/.ssh
+          chmod 600 ~/.ssh/id_rsa
+          
+          ssh-keyscan -t rsa,ecdsa,ed25519 github.com >> ~/.ssh/known_hosts
+
+          echo "--- SSH Debug ---"
+          ssh -T -v git@github.com || true
+
       - name: Checkout source
         uses: actions/checkout@v2
         with:
           ref: master
-
+      
       - name: Setup Node.js
         uses: actions/setup-node@v1
         with:
@@ -25,14 +42,8 @@ jobs:
         env:
           ACTION_DEPLOY_KEY: ${{ secrets.HEXO_DEPLOY_KEY }}
         run: |
-          mkdir -p ~/.ssh/
-          echo "$ACTION_DEPLOY_KEY" | tee ~/.ssh/id_rsa
-          chmod 700 ~/.ssh
-          chmod 600 ~/.ssh/id_rsa
-          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
           git config --global user.email "sdauwangzh@163.com"
           git config --global user.name "Joe"
-          ssh -o StrictHostKeyChecking=no -T git@github.com || true
           npm install hexo-cli -g
           npm install
 
